x-environment: &environment
  MYSQL_DB_LOG: db_log
  MYSQL_DB_AUTOREPORT: db_autoreport
  MYSQL_DB_DATA: NKRRapporteket
  MYSQL_HOST: db
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  FALK_APP_ID: 86
  FALK_EXTENDED_USER_RIGHTS: "[{\"A\":86,\"R\":\"SC\",\"U\":111068},{\"A\":86,\"R\":\"LU\",\"U\":111068},{\"A\":86,\"R\":\"LU\",\"U\":601161},{\"A\":86,\"R\":\"SC\",\"U\":601161}]"
  USERORGID: "pilot"
  SHINYPROXY_USERNAME: test@tester.no
  SHINYPROXY_USERGROUPS: "pilot"
  R_RAP_INSTANCE: "QAC"


services:

  db:
    image: mysql:8
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./dev/db:/docker-entrypoint-initdb.d
    entrypoint:
      sh -c "/usr/local/bin/docker-entrypoint.sh  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - 3306:3306

  app:
    depends_on:
      - db
    image: rygg_test
    ports:
      - 3838:3838
    environment:
      R_RAP_CONFIG_PATH: /app/R
      << : *environment
