x-environment: &environment
  MYSQL_DB_LOG: db_log
  NORDICSCIR_DB: db_data
  MYSQL_DB_AUTOREPORT: db_autoreport
  MYSQL_DB_DATA: ngerreportdatastaging
  MYSQL_HOST: db
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  FALK_APP_ID: 86
  FALK_EXTENDED_USER_RIGHTS: "[{\"A\":86,\"R\":\"SC\",\"U\":111068},{\"A\":86,\"R\":\"LU\",\"U\":111068},{\"A\":86,\"R\":\"LU\",\"U\":601161},{\"A\":86,\"R\":\"SC\",\"U\":601161}]"
  USERORGID: "pilot"
  SHINYPROXY_USERNAME: test@tester.no
  SHINYPROXY_USERGROUPS: "pilot"
  R_RAP_INSTANCE: "QAC"


services:

  db:
    image: mysql:8
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./dev/db:/docker-entrypoint-initdb.d
      - /d/db:/var/lib/mysql
    entrypoint:
      sh -c "
        /usr/local/bin/docker-entrypoint.sh  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    ports:
      - 3306:3306

  app:
    depends_on:
      - db
     image: rapporteket/nger:latest
    ports:
      - 3838:3838
    volumes:
      - ./data-raw/config:/app/R
    environment:
      R_RAP_CONFIG_PATH: /app/R
      << : *environment

  dev:
    depends_on:
      - db
    image: rapporteket/pilot-dev:main
    volumes:
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - .:/home/rstudio/rygg
      - /c/ResultattjenesteGIT:/home/rstudio
      - ../rapbase/.:/home/rstudio/rapbase
      - /c/Users/Lena Ringstad Olsen/.ssh:/home/rstudio/speiler_.ssh
      - /d/mydata:/home/rstudio/mydata
    ports:
      - "8787:8787"
    restart: "no"
    environment:
      << : *environment
      DISABLE_AUTH: "true"
      R_RAP_CONFIG_PATH: /home/rstudio/rygg/data-raw/config

  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080

  rapadm:
    depends_on:
      - db
    image: rapporteket/rapadm:latest
    restart: "no"
    environment:
      << : *environment
    ports:
      - 9011:3838