#' Henter data registrert for Degenerativ Rygg
#'
#' Henter data for Degenerativ Rygg fra "staging" (?)
#'
#'
#' @return RegData data frame
#' @export
#'
RyggRegDataSQL <- function(datoFra = '2007-01-01', datoTil = '2099-01-01'){


  query <- paste0('SELECT
	AlderVedOpr,
	-- Antibiotika,
	AntibiotikaV3,
	-- AntNivOpr,
	-- Arbstatus12mnd,
	-- Arbstatus3mnd,
ArbstatusPreV3,
	ASA,
	SykehusNavn,
	AvdRESH,
	BMI,
  -- Bydelkode,
  -- Bydelsted,
	Dagkirurgi,
	-- EQ5D12mnd,
	-- EQ5D3mnd,
	EQ5DPreV3,
	-- Eqangst12mnd,
	-- Eqangst3mnd,
	EqangstPreV3,
	-- Eqgange12mnd,
	-- Eqgange3mnd,
	EqgangePreV3,
	ErstatningPre,
	FirstTimeClosed,
	-- FistTimeClosed,
	-- Fornoyd12mnd,
	-- Fornoyd3mnd,
	-- HFNavn,
	-- HovedInngrep,
	-- HovedInngreptxt,
	-- Inngrep,
	-- Inngreptxt,
	Kjonn,
	-- KnivtidTot,
	KommuneNr,
	KommuneNavn,
--	Kp3Mnd,
--	KpBlod3Mnd,
--	KpDVT3Mnd,
--	KpInf3Mnd,
--	KpInfDyp12Mnd,
--	KpInfDyp3Mnd,
--	KpInfOverfla3Mnd,
--	KpLE3Mnd,
--	KpLungebet3Mnd,
--	KpMiktProb3Mnd,
--	KpUVI3Mnd,
-- 	Liggedogn,
	MorsmalV3,
	-- Nytte12mnd,
	-- Nytte3mnd,
	-- OpAar,
	OpDato,
--  OpDeUlamin,
--  OpDeFasett,
	OpIndCauda,
	OpIndParese,
	OpIndPareseGrad,
	-- OpIndSme,
	-- OpIndSmeType,
	OpKat,
	-- OpLaminektomi,
	-- OpMikro,
	-- OpProlap,
	OpTilgangV3,
	-- OswTot12mnd,
	-- OswTot3mnd,
	OswTotPre,
	PeropKomp,
	PeropKompAnafy,
	PeropKompDura,
	PeropKompFeilnivSide,
	PeropKompFeilplassImp,
	PeropKompKardio,
	PeropKompNerve,
	PeropKompResp,
	PeropKompTransfuBlodning,
	PasientID,
	-- Region,
	-- Reop90d,
	ReopUnderOpph,
	RfDegenListeseMM,
	RfSentr,
	RfSpondtypeDegen,
	RokerV3,
	RvCt,
	-- RvDiscogr,
	-- RvDpregblok,
	RvFunksjo,
	RvMr,
	-- RvRadigr,
	RvRtgLscol,
	Saardren,
	SivilStatusV3,
	-- SmBe12mnd,
	-- SmBe3mnd,
	SmBePre,
	-- SmHypp12mnd,
	-- SmHypp3mnd,
	SmHyppPre,
	-- SmRy12mnd,
	-- SmRy3mnd,
	SmRyPre,
	-- SmSti12mnd,
	-- SmSti3mnd,
	SmStiPre,
	surgeonform_LIGGEDOEGN_POSTOPERATIV,
	surgeonform_LIGGEDOEGN_TOTALT,
	Sykd,
	SykdAndreRelevanteSykdBechtrew,
	SykdAnnenendokrin,
	SykdAnnenreumatisk,
	SykdCerebrovaskular,
	SykdDepresjonAngst,
	SykdGeneralisertSmSyndr,
	SykdHjertekar,
	SykdHoftekneartose,
	SykdHypertensjon,
	SykdKreft,
	SykdKroniskLunge,
	SykdKroniskNevrologisk,
	-- SykdKroniskSmerterMuskelSkjelettsyst,
	SykdOsteoporose,
	SykDprebetesMellitus,
	SykdReumatoidartritt,
	SykdVaskularClaudicatio,
	-- Sykehustype,
	SykemeldVarighPreV3,
	SymptVarighRyggHof,
	SympVarighUtstr,
	TidlIkkeOp,
	TdllOpAnnetNiv,
	TidlOpsammeNiv,
	-- TideOp12mnd,
	-- TideOp3mnd,
	-- TidlOpr,
	-- TidlOprAntall,
	UforetrygdPre,
	Utd,
	-- Utfylt12Mnd,
	-- Utfylt3Mnd,
	UtskrivelseDato,
	Vekt
FROM AlleVarNum
  WHERE OpDato >= \'', datoFra, '\' AND OpDato <= \'', datoTil, '\'')

#FROM Uttrekk_Rapport ')

RegData <- rapbase::LoadRegData(registryName="rygg", query=query, dbType="mysql")
#RegDataALLE <- rapbase::LoadRegData(registryName="rygg",
#                                    query='SELECT * FROM AlleVarNum', dbType="mysql")
return(RegData)
}


